default_platform(:ios)

platform :ios do
  desc "Run UI Tests"
  lane :test do
    scan(
      scheme: "russ5",
      device: "iPhone 14 Pro",
      clean: true,
      code_coverage: true,
      result_bundle: true
    )
  end

  desc "Submit to BrowserStack"
  lane :browserstack do
    build_ios_app(
      scheme: "russ5",
      export_method: "development"
    )
    
    upload_to_browserstack_app_automate(
      browserstack_username: ENV["BROWSERSTACK_USERNAME"],
      browserstack_access_key: ENV["BROWSERSTACK_ACCESS_KEY"],
      file_path: lane_context[SharedValues::IPA_OUTPUT_PATH]
    )
  end
end