name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-latest
    env:
      BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
      BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
      
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Ruby for fastlane
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'
        
    - name: Install fastlane
      run: |
        gem install fastlane
        gem install xcpretty
        
    - name: Install BrowserStack app-automate
      run: |
        mkdir -p $HOME/.browserstack
        echo "{ \"username\": \"$BROWSERSTACK_USERNAME\", \"key\": \"$BROWSERSTACK_ACCESS_KEY\" }" > $HOME/.browserstack/config.json
        
    - name: Build and Test
      run: |
        xcodebuild -scheme "russ5" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 14 Pro' clean build test | xcpretty
        
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: ~/Library/Developer/Xcode/DerivedData/**/Logs/Test/*.xcresult