name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-13
    env:
      BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
      BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
      
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Ruby for fastlane
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'
        
    - name: Install fastlane
      run: |
        gem install fastlane
        gem install xcpretty
        
    - name: Install BrowserStack app-automate
      run: |
        mkdir -p $HOME/.browserstack
        echo "{ \"username\": \"$BROWSERSTACK_USERNAME\", \"key\": \"$BROWSERSTACK_ACCESS_KEY\" }" > $HOME/.browserstack/config.json
        
    - name: Check Xcode project format
      run: |
        # Print Xcode version
        xcodebuild -version
        
        # Check if the project can be opened
        if ! xcodebuild -list -project russ5.xcodeproj &>/dev/null; then
          echo "Project format is incompatible. Attempting to convert..."
          # Try to convert the project format if needed
          plutil -convert xml1 russ5.xcodeproj/project.pbxproj
        fi
        
    - name: Build and Test
      run: |
        # Try to list available schemes
        echo "Available schemes:"
        xcodebuild -list -project russ5.xcodeproj || true
        
        # Try to list available destinations
        echo "Available destinations:"
        xcodebuild -showdestinations -project russ5.xcodeproj || true
        
        # Use a more compatible approach with project format
        xcodebuild -project russ5.xcodeproj -scheme "russ5" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 14' -allowProvisioningUpdates -allowProvisioningDeviceRegistration clean build || true
        
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: ~/Library/Developer/Xcode/DerivedData/**/Logs/Test/*.xcresult