name: Minimal Workflow

on:
  push:
    branches: [ main, simplified-cicd ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Run a simple command
        run: echo "Hello, world!"