name: Simplified Safari Extension Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build Safari Extension
    runs-on: macos-latest
    timeout-minutes: 10

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Select Xcode 16.2
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.2'

    - name: Setup Ruby and Node.js
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'
        bundler-cache: true
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: |
        gem install fastlane
        npm install

    - name: Setup SSH key
      env:
        SSH_KEY: ${{ secrets.SSH_KEY }}
        MATCH_GIT_URL: ${{ secrets.MATCH_GIT_URL }}
      run: |
        # Setup SSH directory and key with proper permissions
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        echo "$SSH_KEY" | base64 -d > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        
        # Add GitHub to known hosts
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        chmod 644 ~/.ssh/known_hosts
        
        # Set GIT_SSH_COMMAND environment variable
        export GIT_SSH_COMMAND="ssh -i ~/.ssh/id_ed25519 -o IdentitiesOnly=yes -o StrictHostKeyChecking=accept-new"
        echo "GIT_SSH_COMMAND=$GIT_SSH_COMMAND" >> $GITHUB_ENV
        echo "MATCH_GIT_URL=$MATCH_GIT_URL" >> $GITHUB_ENV

    - name: Build with simplified fastlane
      env:
        TEAM_ID: ${{ secrets.TEAM_ID }}
        FASTLANE_APPLE_ID: ${{ secrets.FASTLANE_APPLE_ID }}
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
      run: |
        # Run simplified build
        bundle exec fastlane build_simple

    - name: Upload build artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: safari-extension-build
        path: |
          ./build/logs/**
          ./build/derived/**
        if-no-files-found: warn
        retention-days: 3
