name: Safari Extension Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build Safari Extension
    runs-on: macos-latest
    timeout-minutes: 15

    steps:
    - name: Show installed Xcodes
      run: |
        printf "Installed Xcode versions:\n"
        ls /Applications | grep -o 'Xcode.*\.app'
    - name: Select Xcode 16.2
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.2'

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Build and verify Safari Extension
      run: npm run ci

    - name: Upload build artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: safari-extension
        path: |
          ./logs/**
          ./dist/**
        if-no-files-found: warn
        retention-days: 7
